name: Analyze Hooks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  hook:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Analyze Hooks
        uses: tequdev/xrpl-hook-fee-actions@v1.0.1-beta
        with:
          inPath: contracts
